# conf/config.yaml
# 默认为True, 控制台打印消息
debug: true

# 日志保留天数
log_days: 3

# 指定进程数
process_num: 4

# 宠汪汪进程数
joy_process_num: 1

# 拼图签到进程数
jd_puzzle_process_num: 1

# 京东COOKIES
jd_cookies:
  - pt_pin=;pt_key=;

# 东东农场是否使用水滴换豆卡, 100水滴换20京豆
jd_farm_bean_card: false

# 东东农场每天保留多少水滴, 用于明天的十次浇水任务
jd_farm_retain_water: 80

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: null
  # TG用户ID
  tg_user_id: null
  # push+ token: https://pushplus.hxtrip.com/
  push_plus_token: null

  # push+ group 一对多推送才需要次配置
  push_plus_group: null

  # 依次填上corpid的值,corpsecret的值,touser的值,agentid,media_id的值，注意用,号隔开。
  qywx_am: null

# 在此列表中的脚本, 将不会加入到定时任务中, 如需立即生效, 请手动执行命令: docker-entrypoint
crontab_exclude_scripts:
  - jd_bean_indiana.py


# 京东试用商品分类, 英文逗号分隔, 可选列表: 全部商品,家用电器,手机数码,电脑办公,家居家装,美妆护肤,服饰鞋包,母婴玩具,生鲜美食,图书音像,钟表奢品,个人护理,家庭清洁,食品饮料.更多惊喜
jd_try_cid_list: 家用电器, 手机数码, 电脑办公, 家居家装

# 京东试用类型, 英文逗号分隔, 可选列表: 全部试用,普通试用,闪电试用,30天试用
jd_try_type_list: 普通试用,闪电试用

# 京东试用商品最低价格
jd_try_min_price: 100

# 京东试用商品提供商品最大数量, 商品提供量多的是辣鸡商品
jd_try_goods_count: 10

# 京东试用商品过滤关键词, 用@分隔
jd_try_filter_keywords: 教程@软件