# conf/config.yaml
# 默认为True, 控制台打印消息
debug: true

# 指定进程数
process_num: 4

jd_cookies:
  - pt_pin=;pt_key=;

# 种豆得豆助力码
jd_planting_code:
  # 一行一个, 顺序无所谓。
  - xxx


# 京东->东东农场互助吗
jd_farm_code:
  - xxx

# 东东农场是否使用水滴换豆卡, 100水滴换20京豆
jd_farm_bean_card: false

# 东东农场每天保留多少水滴, 用于明天的十次浇水任务
jd_farm_retain_water: 80


# 金果摇钱树邀请码
jd_money_tree_share_pin:
  - xxx


# 东东工厂互助码
jd_factory_share_code:
  - Txxx


# 京喜农场互助码
jx_farm_share_code:
  - xxxx

# 京喜工厂互助码
jx_factory_share_code:
  - xxx


# 闪购盲盒互助码
jd_sgmh_share_code:
  - xxx

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: 1xxx
  # TG用户ID
  tg_user_id: xxx


# 请求头, 默认不需要修改
user_agent: jdapp;iPhone;10.0.2;14.3;network/wifi;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1