# conf/config.yaml
# 默认为True, 控制台打印消息
debug: true

jd_cookies:
  - pt_pin=%E694bae;pt_key=AAJg26wqb0ghburg;



# 种豆得豆助力码
jd_planting_code:
  # 一行一个, 顺序无所谓。
  - mlrdw3aw26j3x3vxi2qvp7xj5llrsmtd3tde64i


# 京东->东东农场互助吗
jd_farm_code:
  - f9a5389ab473423e83a746e03a82dddc


# 金果摇钱树邀请码
jd_money_tree_share_pin:
  - kWYkAjeTZGUiPhaXh5w03sAdoUJQ3Dik


# 东东工厂互助码
jd_factory_share_code:
  - T0225KkcRRYR_QbSIkmgkPUDJQCjVWnYaS5kRrbA


# 京喜农场互助码
jx_farm_share_code:
  - {"smp":"c8e2ae8fbde016a8c9420b9162d75b3d","active":"jdnc_1_3yuanmitao210616_2","joinnum":1}

# 京喜工厂互助码
jx_factory_share_code:
  - meal4nfI36-aCltW4_iEsA==


# 闪购盲盒互助码
jd_sgmh_share_code:
  - T020aETDmJ66I9xO9rVQxqZfCjVQmoaT5kRrbA

# 消息通知
notify:
  # TG机器人Token
  tg_bot_token: 1791422745:AAHVmR8dwzrGGh0wa7skWUte7ns9IXZ3aEM
  # TG用户ID
  tg_user_id: 1807924672


# 请求头, 默认不需要修改
user_agent: jdapp;iPhone;10.0.2;14.3;network/wifi;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1